name: Android UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  androidTest:
    name: Run Espresso UI Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download Android SDK
      uses: android-actions/setup-android@v2

    - name: Accept Licenses
      run: yes | sdkmanager --licenses

    - name: Create Emulator
      run: |
        sdkmanager "system-images;android-33;google_apis;x86_64"
        avdmanager create avd -n test -k "system-images;android-33;google_apis;x86_64" --device "pixel_3a"
        echo "no" | emulator -avd test -no-audio -no-window &
        adb wait-for-device

    - name: Run Espresso Tests
      run: ./gradlew connectedAndroidTest

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: app/build/reports/androidTests/connected/
